server:
    port: 80
serial:
    dummy: false
    port: /dev/ttyAMA0
    baudrate: 38400
network:
    frequencyChannel: 0
    networkId: 46406
    address: 1
    security: 0
state:
    clientCheck: false
    clientCheckInterval: 30000
    clientTimeOut: 60 # in s.
broker:
    impl: udp
    amqp:
        host: 192.168.1.4
        port: 5672
        login: domotix
        password: domotix
        vhost: /domotix
    udp:
        inhost: 192.168.1.4
        inport: 5555
        outhost: 192.168.1.255
        outport: 5556
    zmq:
        host: 192.168.1.4
        port: 4000
    faye:
        host: 192.168.1.4
        port: 4000
        path: domotix
udpBridge:
    host: 192.168.1.4
    port: 5555
couchDB:
    host: 192.168.1.4
    port: 5984
thingspeak:
    host: api.thingspeak.com
    port: 80
    securehost: https://api.thingspeak.com
    channels:
        8141:
            writeApiKey: DV1CSLVQ3QIRV0K0
            readApiKey: 0975Z0F5ERBEUNK9
        14164:
            writeApiKey: CX3JT3EGVNMNWDLX
            readApiKey: HY9GQMVC4NEDU5IV
        14293:
            writeApiKey: Y2I37MDE6X6TDP7V
            readApiKey: 3BVPCR69485ZL1I2        
        14320:
            writeApiKey: 8VH430NK9IUMWN2Q
            readApiKey: LZCI2SW058UYLBUU
    fields: # productcode / address / registerId:endpoint
        0000006400000001/2/12:0:
            channelId: 8141
            fieldId: field1
            unit: 0
        0000006400000001/2/12:1:
            channelId: 8141
            fieldId: field2
            unit: 1
        0000006400000001/2/20:0:
            channelId: 14164
            fieldId: field2
            unit: 0        
        0000006400000001/2/14:0:
            channelId: 14293
            fieldId: field2
            unit: 0        
        0000006400000001/2/22:0:
            channelId: 14320
            fieldId: field2
            unit: 0
        0000006400000002/3/12:0:
            channelId: 14164
            fieldId: field1
            unit: 0
plugins:
    temperature:
    pressure:
        compensationAltitude: -36
        standardPressure: 977 # 1013 + compensationAltitude
        minPressure: 944 # 980 + compensationAltitude
        maxPressure: 1004 # 1040 + compensationAltitude
		
